### ISSUE TITLE
Rename "Maple" to something else (due to Trademark issues)

### ISSUE THREAD

**Issue by lukechu10** [lukechu10/sycamore#70]
It appears that Maple is already a registered trademark: https://maplesoft.com/products/Maple/

We might have to change the name to something else. Suggestions are welcome

**Comment by parker-codes** [comment]
What was the inspiration for the name originally? Without knowing, I can list what comes to mind:

- Sap (is a little close to Sapper, a JS framework)
- MapleRs (skirts around any infringement issues)
- Wilt (initially negative connotation of a common Maple tree disease, but follows suit with "Rust")

**Comment by lukechu10** [comment]
> What was the inspiration for the name originally

- I was looking at other frameworks, notably Yew and Elm and they were both trees. I know that the name Yew was inspired by Elm because Yew uses MVU (Elm architecture). Even though Maple does not use MVU, I thought it would be cool to name the framework after a tree.
- The next two are a bit silly but I might as well include them anyways. If you are familiar with Pokemon games, you would know that all the professors are named after a tree (e.g. Oak, Rowan, Juniper etc...). Since Pokemon professors help you become a Pokemon trainer, a web framework helps you become a productive web developer.
- I had a stuff animal (and I still have it in fact) that I was quite fond of. He's called Maple because he likes maple syrup.

> * MapleRs (skirts around any infringement issues)

Yes that could be a possibility. I was thinking of splitting up the `maple-core` crate anyways. Perhaps we could create a new `maple-rs` crate and `maple-core` could become where the reactive primitives are defined so they can be used on other non `wasm32` targets as well.

There are, however, a few downsides. The first being that the name `maple` is already taken on crates.io. Second, although it might bypass infringement issues, I don't want to have this hanging over my head. Lastly, it's bad for SEO (kind of like how when you search "Rust" on Google, you end you getting the Rust video game) as well as being a possible source of confusion.

**Comment by parker-codes** [comment]
I see what you mean. It will be pretty difficult to find an open tree name, I would think. For example, I tried to find a tree that was "fast" and thought of bamboo, but that's already taken!

**Comment by lukechu10** [comment]
Possible name: "Sycamore"

**Comment by parker-codes** [comment]
I like it! The tree itself has some negative outlook, but the name is well-sounding and fits your rubric.

**Comment by lukechu10** [comment]
I would like to get any name-change finalized before 0.5 release so that we stop using the existing names on crates.io.
